# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6ffcc00b3025b52de2cf2c2d0ca68672d1b38d68ee9d6d6f0e19b1e83a0b2fbf3c6dc03e84a3ca4e85938f5aecb3fdec56f7a32b845e14f83b9080aa3b3d738f

test:
  secret_key_base: e3f6731ea107713d0bd9b601c9d5ded3064572dd684f3518130c2b93777924f1415ef83f133c6d9915aefdd7e5733db21c07f12c7692feab5dbb935249e6bc6c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
